[package]
name = "turingfeeds"
version = "0.1.0"
authors = ["Charles Chege <charleschege@protonmail.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.2.0", features = ["attributes"] }
uuid = { version = "0.7.4", features = ["v4"] }
custom_codes =  { path = "../custom_codes" } #"1.2.3"
timelite = "1.0.4"
tai64 = "3.1.0"
seahash = "3.0.6"
redactedsecret = { path = "../RedactedSecret" } #"0.4.1"
walkdir = "2.2.9"
ron = "0.5.1"