[package]
name = "turingfeeds-repo"
version = "1.0.0-beta.1"
authors = ["Charles Chege <charleschege@protonmail.ch>"]
edition = "2018"

[workspace]
members = [
	"TuringFeeds",
	"ClientTester",
	"TuringFeedsHelpers",
]

[[bin]]
name = "turingfeeds"
path = "TuringFeeds/src/bin/turingfeeds.rs"

[dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
