[package]
name = "turingfeeds-repo"
version = "1.0.0-beta.1"
authors = ["Charles Chege <charleschege@protonmail.ch>"]
edition = "2018"

[workspace]
members = [
	"TuringFeeds",
	"TuringFeedsHelpers",
	"TuringFeedsServer",
]

[[bin]]
name = "turingfeeds-server"
path = "TuringFeedsServer/src/bin/server.rs"
