[tasks.default]
dependencies = ["build"]

[tasks.build]
command = "cargo"
args = ["build"]
watch = {}


[tasks.check]
command = "cargo"
args = ["check"]
dependencies = ["fmt"]
watch = {}

[tasks.fmt]
command = "cargo"
args = ["fmt"]